# /home/digilab/timesheet/client/netlify.toml
[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://timesheet-c4mj.onrender.com/api/:splat" # Your backend URL
  status = 200
  force = true
  methods = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
 